version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build
artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - dist/server.js
    - tsconfig.json
    - package.json
    - appspec.yml
    - 'node_modules/**/*'